<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="10" total="19" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="TestNG Suite" duration-ms="74281" started-at="2016-12-22T06:10:40Z" finished-at="2016-12-22T06:11:55Z">
    <groups>
    </groups>
    <test name="Title Validation" duration-ms="74281" started-at="2016-12-22T06:10:40Z" finished-at="2016-12-22T06:11:55Z">
      <class name="core.DBTest">
        <test-method status="PASS" signature="browserOpen()[pri:0, instance:core.DBTest@365474b4]" name="browserOpen" is-config="true" duration-ms="7511" started-at="2016-12-21T22:10:40Z" finished-at="2016-12-21T22:10:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="813" started-at="2016-12-21T22:10:48Z" finished-at="2016-12-21T22:10:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.learn2test.net]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[learn2test.net]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="747" started-at="2016-12-21T22:10:49Z" finished-at="2016-12-21T22:10:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.02]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.alegro.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[www.alegro.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="699" started-at="2016-12-21T22:10:50Z" finished-at="2016-12-21T22:10:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.03]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.alegro.net]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[www.alegro.net]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "www.alegro.net"
     but: was ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "www.alegro.net"
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="5107" started-at="2016-12-21T22:10:50Z" finished-at="2016-12-21T22:10:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.04]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.learn2test.net]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[learn2test.net]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "learn2test.net"
     but: was "Back Pain Management Guide | Everyday Health"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "learn2test.net"
     but: was "Back Pain Management Guide | Everyday Health"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="3189" started-at="2016-12-21T22:10:55Z" finished-at="2016-12-21T22:10:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.05]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.ebay.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Electronics]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Electronics"
     but: was "Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Electronics"
     but: was "Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1598" started-at="2016-12-21T22:10:59Z" finished-at="2016-12-21T22:11:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.06]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.w3schools.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[W3Schools Online Web Tutorials]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1054" started-at="2016-12-21T22:11:00Z" finished-at="2016-12-21T22:11:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.07]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.w3schools.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[W3Schools Online Web Tutorial ]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "W3Schools Online Web Tutorial "
     but: was "W3Schools Online Web Tutorials"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "W3Schools Online Web Tutorial "
     but: was "W3Schools Online Web Tutorials"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1436" started-at="2016-12-21T22:11:01Z" finished-at="2016-12-21T22:11:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.08]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.google.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Google]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1214" started-at="2016-12-21T22:11:03Z" finished-at="2016-12-21T22:11:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.09]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.google.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Google1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Google1"
     but: was "Google"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Google1"
     but: was "Google"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="7098" started-at="2016-12-21T22:11:04Z" finished-at="2016-12-21T22:11:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.yahoo.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Yahoo]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="11579" started-at="2016-12-21T22:11:11Z" finished-at="2016-12-21T22:11:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.yahoo.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Yaho]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Yaho"
     but: was "Yahoo"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Yaho"
     but: was "Yahoo"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="2801" started-at="2016-12-21T22:11:23Z" finished-at="2016-12-21T22:11:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.kirkwood.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Kirkwood Mountain | Rare Earth | kirkwood.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1371" started-at="2016-12-21T22:11:25Z" finished-at="2016-12-21T22:11:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.13]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.kirkwood.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Kirkwood Mountain | Rare Earth | kirkwood.co]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Kirkwood Mountain | Rare Earth | kirkwood.co"
     but: was "Kirkwood Mountain | Rare Earth | kirkwood.com"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Kirkwood Mountain | Rare Earth | kirkwood.co"
     but: was "Kirkwood Mountain | Rare Earth | kirkwood.com"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="1967" started-at="2016-12-21T22:11:27Z" finished-at="2016-12-21T22:11:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.14]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://stackoverflow.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Stack Overflow]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="724" started-at="2016-12-21T22:11:29Z" finished-at="2016-12-21T22:11:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.15]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://stackoverflow.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Stack Overflo]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Stack Overflo"
     but: was "Stack Overflow"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Stack Overflo"
     but: was "Stack Overflow"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="7693" started-at="2016-12-21T22:11:29Z" finished-at="2016-12-21T22:11:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.speedtest.net/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Speedtest.net by Ookla - The Global Broadband Speed Test]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="8782" started-at="2016-12-21T22:11:37Z" finished-at="2016-12-21T22:11:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.17]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://www.speedtest.net/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Speedtest.net by Ookla - The Global Broadband Speed Tes]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Speedtest.net by Ookla - The Global Broadband Speed Tes"
     but: was "Speedtest.net by Ookla - The Global Broadband Speed Test"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Speedtest.net by Ookla - The Global Broadband Speed Tes"
     but: was "Speedtest.net by Ookla - The Global Broadband Speed Test"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="3826" started-at="2016-12-21T22:11:46Z" finished-at="2016-12-21T22:11:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.copart.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Copart USA - Leader in Online Salvage & Insurance Auto Auctions]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="FAIL" signature="titleValidation(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:core.DBTest@365474b4]" name="titleValidation" duration-ms="2861" started-at="2016-12-21T22:11:50Z" finished-at="2016-12-21T22:11:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-001.19]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.copart.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Copart USA - Leader in Online Salvage & Insurance Auto Auction]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is "Copart USA - Leader in Online Salvage & Insurance Auto Auction"
     but: was "Copart USA - Leader in Online Salvage & Insurance Auto Auctions"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is "Copart USA - Leader in Online Salvage & Insurance Auto Auction"
     but: was "Copart USA - Leader in Online Salvage & Insurance Auto Auctions"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DBTest.titleValidation(DBTest.java:35)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="browserQuit()[pri:0, instance:core.DBTest@365474b4]" name="browserQuit" is-config="true" duration-ms="2043" started-at="2016-12-21T22:11:53Z" finished-at="2016-12-21T22:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserQuit -->
      </class> <!-- core.DBTest -->
    </test> <!-- Title Validation -->
  </suite> <!-- TestNG Suite -->
</testng-results>
